
language: php
php:
  - 7.1.9
  
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
  
matrix:
  fast_finish: true


before_install:
  - composer self-update

install:
  - composer install
  - php bin/phpunit