
language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
  
matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - composer self-update

install:
  - composer install
  - php bin/phpunit